### PR TITLE
Implement restoring beatmaps from graveyard

### PR DESCRIPTION
**Pull request by bdach**
While this performs the same operation as web-10 did when resurrecting, the operation is a little different; in stable, the actual upload request would be the one that would resurrect the map, rather than the initial "give me IDs" request. In here it's the converse.

The only reason for doing this that I can give is that it is a little easier to have things this way; having the graveyard logic on the first request avoids smearing it across, because web-10 handled it half-here half-there (the initial request would check whether you have slots to resurrect, but only the actual submission would resurrect). If that is not desirable then I can probably make it work the other way around too, at some code quality expense.

### CODE REVIEW

**Comment by peppy** [comment]
I guess a further consideration would be giving the user control over whether the revive occurs, rather than having it implicit. The way you have things setup seems like that could be added with minimal fuss.

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
> I guess a further consideration would be giving the user control over whether the revive occurs, rather than having it implicit

I could, but not sure I follow why that would be desired. I'm not sure what was the original rationale of putting the upload cap in place was, but allowing free uploads of graved maps - especially with versioning now active - could lead to some degree of abuse.

**Comment by peppy** [comment]
I just mean having the user have a "Upload and revive" button before the revive happens. But now that I think about it, you probably already have something like that? I think stable's flow does that already.

**Comment by bdach** [comment]
> I just mean having the user have a "Upload and revive" button before the revive happens. But now that I think about it, you probably already have something like that

Oh if you mean just changing client-side copy then sure, that can be done.

**Pull request merged**
